// Generated by CoffeeScript 2.4.1
(function() {
  // CSS Animation Checkbox URL Parameter Action CACUPA
  var actionUrl;

  actionUrl = function(r, g, b) {
    var arrayRemoveAll, parameterSeperator, updateUrl, url, values;
    // Setup
    // inputName = inputName || 'animate' # CSS Selector: input[name="animate"]
    // urlParameterName = urlParameterName || 'action' # URL Parameter: www/?action=A&B&C
    // urlSeperator = urlParameterName + '='
    parameterSeperator = '-';
    // inputSelector = 'input[name="' + inputName + '"]'
    // checkbox = document.querySelectorAll(inputSelector)
    // labelSelector = 'label'
    // label = document.querySelectorAll(labelSelector)
    url = window.location.href;
    // Split URL
    // values = []
    // if url.includes(urlSeperator)
    // 	urlSplit = url.split(urlSeperator).pop()
    // 	if urlSeperator < urlSplit
    // 		values = urlSplit.split(parameterSeperator)
    values = [r, g, b];
    // Activate Checkbox via URL Parameter
    // i = 0
    // checkbox.forEach ->
    // 	if values.includes(checkbox[i].value)
    // 		checkbox[i].checked = true
    // 	i++

    // Add Event Listeners to all Labels 
    // i = 0
    // label.forEach -> 
    // 	label[i].addEventListener("click", ->
    // 		updateUrl()
    // 	)
    // 	i++

    // Completely remove a Value from an Array
    arrayRemoveAll = function(array, value) {
      return array.filter(function(val) {
        return val !== value;
      });
    };
    // Update URL Parameter
    return updateUrl = function() {
      return setTimeout(function() {
        var updatedUrlParameter, urlParameter;
        // Check all Checkboxes and update 'values'-Array
        // i = 0
        // checkbox.forEach ->
        // 	if (checkbox[i].checked)
        // 		if !values.includes(checkbox[i].value)
        // 			values.push(checkbox[i].value)
        // 	else
        // 		if values.includes(checkbox[i].value)
        // 			values = arrayRemoveAll(values, checkbox[i].value)
        // 	i++  

        // Join and push the fresh Values
        urlParameter = values.join(parameterSeperator);
        // urlSep = urlSeperator
        // if !urlParameter
        // 	urlParameter = '.' # Current Directory (invisible in URL)
        updatedUrlParameter = "?" + urlParameter;
        return window.history.pushState(updatedUrlParameter, 'CACUPA', updatedUrlParameter);
      }, 0); // Lucky Quickfix
    };
  };

  
  // updateUrl()

  // Call CACUPA
  actionUrl();

  // Check URL über Service Worker, bis dahin "?" 
// Oder dynamisch mit if Service Worker is true
// rgb.li/r3g2b1

}).call(this);
