// Generated by CoffeeScript 2.4.1
(function() {
  //#
  //region service worker
  var createColorGrid, createColorPng, debugLog, disableFullScreenColor, enableFullScreenColor, enableFullScreenColorPng, getColorCodeFromUrl, home, isFullScreen, onElementClick, onPageLoad, pushWindowHistoryState, randomColorCode, setup, stateSwitch, userHistory, validateColorCode;

  window.onload = function() {
    'use strict';
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('./sw.js').then(function(registration) {
        console.log('Service Worker Registered', registration);
      }).catch(function(err) {
        console.log('Service Worker Failed to Register', err);
      });
    }
  };

  //endregion

  //#
  //region setup
  userHistory = [];

  debugLog = true;

  debugLog = function(log) {
    if (debugLog) {
      return console.log(log);
    }
  };

  onPageLoad = function() {
    debugLog("onPageLoad()");
    setup();
    return getColorCodeFromUrl();
  };

  setup = function() {
    debugLog("setup()");
    createColorGrid();
    return window.addEventListener('popstate', function(e) {
      debugLog('setup() -> popstate event');
      return stateSwitch();
    });
  };

  //endregion

  //#
  //region state management
  isFullScreen = function() {
    var fullScreenState;
    debugLog('isFullScreen()');
    if (document.getElementById('fullScreenColor') === null) {
      return fullScreenState = false;
    } else {
      return fullScreenState = true;
    }
  };

  stateSwitch = function() {
    debugLog('stateSwitch()');
    // browser history state change by user
    if (isFullScreen()) {
      debugLog('stateSwitch() -> if isFullScreen()');
      return home();
    } else {
      debugLog('stateSwitch() -> else');
      return getColorCodeFromUrl('#');
    }
  };

  home = function() {
    debugLog('home()');
    return disableFullScreenColor('/.');
  };

  pushWindowHistoryState = function(state3) {
    debugLog('pushWindowHistoryState("' + state3 + '")');
    if (userHistory.length === 0) {
      userHistory.push(state3);
      return window.history.pushState(state3, state3, state3);
    } else {
      return debugLog("else " + userHistory);
    }
  };

  // debugLog('pushWindowHistoryState("' + state3 + '") -> window.history.state == ' + window.history.state)
  onElementClick = function(event) {
    var color, tokens;
    debugLog('onElementClick(' + event + ')');
    tokens = event.target.getAttribute("href").split("#");
    color = "#" + tokens[1];
    return enableFullScreenColor(color);
  };

  getColorCodeFromUrl = function() {
    var query, url;
    debugLog("getColorCodeFromUrl('#')");
    url = window.location.href;
    if (url.includes('#')) {
      debugLog("getColorCodeFromUrl -> if url.includes('#')");
      query = '#' + url.split('#')[1];
      return validateColorCode(query);
    }
  };

  //endregion

  //#
  //region color
  randomColorCode = function(colorType) {
    debugLog('randomColorCode(colorType)');
    colorType = colorType || 'hex';
    if (colorType === 'hex') {
      return '#' + (0x1000000 + (Math.random()) * 0xffffff).toString(16).substr(1, 6);
    }
  };

  createColorGrid = function() {
    var autoColorGrid, i, topColorGrid;
    debugLog('createColorGrid()');
    i = 1;
    (topColorGrid = function() {
      return debugLog('createColorGrid() -> selectedColors()');
    })();
    return (autoColorGrid = function() {
      var colorSquares, colors, divArray, randomColor, results;
      debugLog('createColorGrid() -> autoColors()');
      colorSquares = 1000;
      divArray = new Array;
      colors = document.getElementById('colors');
      results = [];
      while (i < colorSquares) {
        divArray[i] = document.createElement('div');
        divArray[i].id = 'color' + i;
        divArray[i].style.backgroundColor = randomColor = randomColorCode('hex');
        divArray[i].className = 'color';
        divArray[i].setAttribute('href', "" + randomColor);
        divArray[i].addEventListener("click", onElementClick);
        colors.appendChild(divArray[i]);
        results.push(i++);
      }
      return results;
    })();
  };

  validateColorCode = function(colorCode) {
    debugLog('validateColorCode(' + colorCode + ')');
    if (/^#[0-9A-F]{6}$/i.test(colorCode) || /^#([0-9A-F]{3}){1,2}$/i.test(colorCode)) {
      debugLog('validateColorCode(' + colorCode + ') -> ' + colorCode + ' is a valid HEX color code');
      return enableFullScreenColor(colorCode); // return true # 
    }
  };

  createColorPng = function(width, height, colorCode) {
    var canvas, context, image;
    canvas = document.createElement("CANVAS");
    canvas.setAttribute("width", width);
    canvas.setAttribute("height", height);
    context = canvas.getContext("2d");
    context.fillStyle = colorCode;
    context.fillRect(0, 0, width, height);
    image = canvas.toDataURL("image/png");
    image = canvas.toDataURL();
    return image;
  };

  enableFullScreenColor = function(color) {
    var fullScreenColorDiv;
    debugLog("enableFullScreenColor(" + color + ")");
    fullScreenColorDiv = '<div id="fullScreenColor" style="background-color: ' + color + ';">';
    document.getElementById('fullscreen').insertAdjacentHTML('afterbegin', fullScreenColorDiv);
    document.getElementById('fullscreen').style.overflow = 'hidden';
    return pushWindowHistoryState(color);
  };

  disableFullScreenColor = function(pushState) {
    document.getElementById('fullScreenColor').remove();
    document.getElementById('fullscreen').style.overflow = null;
    return window.history.replaceState(null, null, window.location.pathname);
  };

  enableFullScreenColorPng = function(color) {
    var png, pngHTML;
    debugLog("enableFullScreenColor(" + color + ", " + id + ")");
    png = createColorPng(360, 360, color);
    pngHTML = "<img id='colorImage' src='" + png + "' style='position:fixed; width:100vw; height:100vh; image-rendering: pixelated;'>";
    document.getElementById('fullscreen').insertAdjacentHTML('afterbegin', pngHTML);
    return pushWindowHistoryState(color);
  };

  //endregion
  onPageLoad();

  //#
//region notes

// NOW
// fullScreenDiv Rolback
// animation
// png sharing bug 
// structure / png in div
// top colors noscript to coffee
// lazy loading
// metatags
// working home pwa
// ios swipe indikator ausblenden

// 5x Touch Menu
// Bei Fullscreen wird immer zuerst unten eine Menüleiste angezeigt, notch,
// bei erneutem Klick auf die Farbe wird die Menüleiste ausgeblendet
// und kann nur über Browser Back zurückgeholt werden, oder 5x Touch...

// color pwa
// v1.5.0?

// cursor
// https://www.cssscript.com/interacitve-cursor-dot/

// back forward bug: mostly fixed...
// browser-sync second device back forward sync

// Backwards compatible, future proof :)

// Browser-Sync Click Bug
// https://github.com/BrowserSync/browser-sync/issues/49
// https://www.cssscript.com/circle-cursor-pointer/

// cert & key gitignore + documentation

//endregion

}).call(this);
