// Generated by CoffeeScript 2.4.1
(function() {
  // Register Service Worker
  var createColorGrid, debugLog, disableFullScreenColor, enableFullScreenColor, getUrlQuery, home, isFullScreen, onElementClick, onPageLoad, setup, stateSwitch, urlSeperator, validateColorCode, windowHistoryPushState;

  window.onload = function() {
    'use strict';
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('./sw.js').then(function(registration) {
        console.log('Service Worker Registered', registration);
      }).catch(function(err) {
        console.log('Service Worker Failed to Register', err);
      });
    }
  };

  urlSeperator = '#';

  debugLog = true;

  debugLog = function(log) {
    if (debugLog) {
      return console.log(log);
    }
  };

  onPageLoad = function() {
    debugLog("onPageLoad()");
    setup();
    return getUrlQuery(urlSeperator);
  };

  setup = function() {
    debugLog("setup()");
    document.getElementById('fullscreen').insertAdjacentHTML('afterbegin', '<div id="fullScreenColor"></div>');
    createColorGrid();
    return window.addEventListener('popstate', function(e) {
      debugLog('setup() -> popstate event');
      return stateSwitch();
    });
  };

  isFullScreen = function() {
    var fullScreenColor, fullScreenState;
    debugLog('isFullScreen()');
    fullScreenColor = document.getElementById('fullScreenColor');
    fullScreenState = 'unknown';
    if (fullScreenColor.style.height === '0px') {
      debugLog('isFullScreen() -> fullScreenColor.style.height == "0px"');
      return fullScreenState = false;
    } else {
      debugLog('isFullScreen() -> else fullScreenColor.style.height = ' + fullScreenColor.style.height);
      return fullScreenState = true;
    }
  };

  stateSwitch = function() {
    debugLog('stateSwitch()');
    if (isFullScreen()) {
      debugLog('stateSwitch() -> if isFullScreen()');
      return home();
    } else {
      debugLog('stateSwitch() -> else');
      return getUrlQuery('#');
    }
  };

  home = function() {
    debugLog('home()');
    return disableFullScreenColor('/.');
  };

  windowHistoryPushState = function(state3) {
    debugLog('windowHistoryPushState("' + state3 + '")');
    window.history.pushState(state3, state3, state3);
    return debugLog('windowHistoryPushState("' + state3 + '") -> window.history.state == ' + window.history.state);
  };

  enableFullScreenColor = function(color) {
    var fullScreenColor;
    debugLog("enableFullScreenColor(" + color + ")");
    fullScreenColor = document.getElementById('fullScreenColor');
    fullScreenColor.style.backgroundColor = color;
    fullScreenColor.style.height = '100vh';
    document.getElementById('fullscreen').style.overflow = 'hidden';
    return windowHistoryPushState(color);
  };

  disableFullScreenColor = function(pushState) {
    var fullScreenColor;
    fullScreenColor = document.getElementById('fullScreenColor');
    fullScreenColor.style.backgroundColor = null;
    fullScreenColor.style.height = '0px';
    document.getElementById('fullscreen').style.overflow = null;
    return window.history.replaceState(null, null, window.location.pathname);
  };

  onElementClick = function(event) {
    var color, tokens;
    debugLog('onElementClick(' + event + ')');
    tokens = event.target.getAttribute("href").split("#");
    color = "#" + tokens[1];
    return enableFullScreenColor(color);
  };

  getUrlQuery = function(urlSeperator) {
    var query, url;
    debugLog('getUrlQuery("' + urlSeperator + '")');
    urlSeperator = urlSeperator || "?";
    url = window.location.href;
    if (url.includes(urlSeperator)) {
      debugLog('getUrlQuery -> if url.includes(' + urlSeperator + ')');
      query = '#' + url.split(urlSeperator)[1];
      return validateColorCode(query);
    }
  };

  validateColorCode = function(colorCode) {
    debugLog('validateColorCode(' + colorCode + ')');
    if (/^#[0-9A-F]{6}$/i.test(colorCode) || /^#([0-9A-F]{3}){1,2}$/i.test(colorCode)) {
      debugLog('validateColorCode(' + colorCode + ') -> ' + colorCode + ' is a valid HEX color code');
      return enableFullScreenColor(colorCode);
    }
  };

  createColorGrid = function() {
    var autoColorGrid, i, topColorGrid;
    debugLog('createColorGrid()');
    i = 1;
    (topColorGrid = function() {
      return debugLog('createColorGrid() -> selectedColors()');
    })();
    return (autoColorGrid = function() {
      var colorSquares, colors, divArray, randomColor, results;
      debugLog('createColorGrid() -> autoColors()');
      colorSquares = 1000;
      divArray = new Array;
      colors = document.getElementById('colors');
      results = [];
      while (i < colorSquares) {
        divArray[i] = document.createElement('div');
        divArray[i].id = 'color' + i;
        divArray[i].style.backgroundColor = randomColor = '#' + (0x1000000 + (Math.random()) * 0xffffff).toString(16).substr(1, 6);
        divArray[i].className = 'color';
        divArray[i].setAttribute('href', "" + randomColor);
        divArray[i].addEventListener("click", onElementClick); // fixed by Lenny
        colors.appendChild(divArray[i]);
        results.push(i++);
      }
      return results;
    })();
  };

  onPageLoad();

  // NOW
// back forward bug: mostly fixed...
// browser-sync second device back forward sync
// top color grid
// auto color grid

// FUNCTIONS

// Config

// Generate Color Grid
// Animate

// Set URL onClick

// Get Color from URL

// Open Color Screen with Menu

// Open Fullscreen Color

// Menu
// Change Color

// Save Color to Favorites

// State Management
// window.history
// state variable

// Die ersten Farben manuell festlegen!

// Backwards compatible, future proof :)

// pixel perfect squares (and elements)

// Browser-Sync Bug

// cert keys gitignore

}).call(this);
