// Generated by CoffeeScript 2.4.1
(function() {
  /* Hello! */
  var cacheName, filesToCache;

  cacheName = 'hello-pwa';

  filesToCache = ['/manifest.json', '/favicon.ico', '/index.html', '/img/icon.png', '/app2/manifest.json', '/app2/favicon.ico', '/app2/index.html', '/app2/img/icon.png'];

  /* Start the service worker and cache all of the app's content */
  self.addEventListener('install', function(e) {
    e.waitUntil(caches.open(cacheName).then(function(cache) {
      return cache.addAll(filesToCache);
    }));
  });

  /* Serve cached content when offline */
  self.addEventListener('fetch', function(e) {
    e.respondWith(caches.match(e.request).then(function(response) {
      return response || fetch(e.request);
    }));
  });

}).call(this);
