// Generated by CoffeeScript 2.4.1
(function() {
  // RGB Light Service Worker
  var cacheName, filesToCache;

  cacheName = 'rgb-li';

  filesToCache = [];

  /* Start the service worker and cache all of the app's content */
  // '/manifest.json'
  // '/favicon.ico'
  // '/index.html'
  // '/img/icon.png'
  self.addEventListener('install', function(e) {
    e.waitUntil(caches.open(cacheName).then(function(cache) {
      return cache.addAll(filesToCache);
    }));
  });

  /* Serve cached content when offline */
  self.addEventListener('fetch', function(e) {
    e.respondWith(caches.match(e.request).then(function(response) {
      return response || fetch(e.request);
    }));
  });

}).call(this);
